apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: rustapitest
  name: rustapitest
  namespace: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rustapitest
  template:
    metadata:
      labels:
        k8s-app: rustapitest
      name: rustapitest
    spec:
      containers:
        - image: cristianmartella/rustapitest:0.1.0
          imagePullPolicy: Always
          name: rustapitest
      restartPolicy: Always