# Copyright 2025 Cristian Martella
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### File variables
@PAP-HOST = pap-provider.127.0.0.1.nip.io:8080


### 01. Get the policy list
GET http://{{PAP-HOST}}/policy


### 02. Delete a policy
@02_POLICY-ID = ilkcnlyvwt

DELETE http://{{PAP-HOST}}/policy/{{02_POLICY-ID}}


### 03. Create a policy to allow any participant to interact with the rustapitest service
@03_VC-TYPE = RustApiTestCredential
@03_ODRL-ACTION = odrl:use

POST http://{{PAP-HOST}}/policy
Content-Type: application/json

{ 
    "@context": {
        "dc": "http://purl.org/dc/elements/1.1/",
        "dct": "http://purl.org/dc/terms/",
        "owl": "http://www.w3.org/2002/07/owl#",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#"
    },
    "@id": "https://mp-operation.org/policy/common/type",
    "@type": "odrl:Policy",
    "odrl:permission": {
        "odrl:assigner": {
            "@id": "https://www.mp-operation.org/"
        },
        "odrl:target": {
            "@type": "odrl:AssetCollection",
            "odrl:source": "urn:asset",
            "odrl:refinement": [
                {
                    "@type": "odrl:Constraint",
                    "odrl:leftOperand": "http:path",
                    "odrl:operator": {
                        "@id": "http:isInPath"
                    },
                    "odrl:rightOperand": {
                        "@value": "/users",
                        "@type": "xsd:string"
                    }
                }
            ]
        },
        "odrl:assignee": {
            "@type": "odrl:PartyCollection",
            "odrl:source": "urn:user",
            "odrl:refinement": {
                "@type": "odrl:Constraint",
                "odrl:leftOperand": {
                    "@id": "vc:type"
                },
                "odrl:operator": {
                    "@id": "odrl:hasPart"
                },
                "odrl:rightOperand": {
                    "@value": "{{03_VC-TYPE}}",
                    "@type": "xsd:string"
                }
            }
        },
        "odrl:action": {
            "@id": "{{03_ODRL-ACTION}}"
        }
    }
}

### 04. Allow any participant with a UserCredential to manage K8SCluster2 entity type on the data service

@04_VC-TYPE = UserCredential
@04_ODRL-ACTION = odrl:use

@04_ENTITY-TYPE = K8SCluster2

POST http://{{PAP-HOST}}/policy
Content-Type: application/json

{ 
    "@context": {
        "dc": "http://purl.org/dc/elements/1.1/",
        "dct": "http://purl.org/dc/terms/",
        "owl": "http://www.w3.org/2002/07/owl#",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#"
    },
    "@id": "https://mp-operation.org/policy/common/type",
    "@type": "odrl:Policy",
    "odrl:permission": {
        "odrl:assigner": {
            "@id": "https://www.mp-operation.org/"
        },
        "odrl:target": {
            "@type": "odrl:AssetCollection",
            "odrl:source": "urn:asset",
            "odrl:refinement": [
                {
                    "@type": "odrl:Constraint",
                    "odrl:leftOperand": "http:path",
                    "odrl:operator": {
                        "@id": "http:isInPath"
                    },
                    "odrl:rightOperand": {
                        "@value": "/ngsi-ld/v1/entities",
                        "@type": "xsd:string"
                    }
                },
                {
                    "@type": "odrl:Constraint",
                    "odrl:leftOperand": "ngsi-ld:entityType",
                    "odrl:operator": {
                        "@id": "odrl:eq"
                    },
                    "odrl:rightOperand": "{{04_ENTITY-TYPE}}"
                }
            ]
        },
        "odrl:assignee": {
            "@type": "odrl:PartyCollection",
            "odrl:source": "urn:user",
            "odrl:refinement": {
                "@type": "odrl:Constraint",
                "odrl:leftOperand": {
                    "@id": "vc:type"
                },
                "odrl:operator": {
                    "@id": "odrl:hasPart"
                },
                "odrl:rightOperand": {
                    "@value": "{{04_VC-TYPE}}",
                    "@type": "xsd:string"
                }
            }
        },
        "odrl:action": {
            "@id": "{{04_ODRL-ACTION}}"
        }
    }
}
